### ISSUE TITLE
Typo in workshop name

### ISSUE THREAD

**Issue by bojoer** [ismnoiet/nodeschool-workshops-manager#4]
Hey,

There is a typo in one of the workshop names and it is not worth a pull request i think.

The workshop **nodebot-workshop** is spelled **nodebo**_o_**t-workshop** so it won't install using this nice tool.

Please fix this.

Kind Regards,
Bojoer.

**Comment by ismnoiet** [comment]
Thank you @bojoer for reporting that.
It is fixed now.
